########################################################################################################################
#CSC_226 Vankirkj A03 https://docs.google.com/document/d/1GBoa46-L9xcG_BWwYVxoecRyPn8GjxnTeoA-_Hp6lUk/edit?usp=sharing
########################################################################################################################

import turtle

def drawsquare():  #makes the base of the skyscraper
    square=turtle.Turtle()
    square.hideturtle()
    square.color(115, 134, 120)
    square.penup()
    square.setpos(0, -70)
    square.pendown()
    square.begin_fill()
    for side in range(2):
        square.forward(200)
        square.left(90)
        square.forward(300)
        square.left(90)
    square.end_fill()

    """
    This is just creating the base of the skyscraper
    """
def window1(): #makes the windows on the skyscraper
    glass = turtle.Turtle()
    glass.color('white')
    glass.penup()
    glass.hideturtle()
    glass.setpos(30,-20)
    glass.begin_fill()
    glass.speed(10)
    for side in range (4):
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(40)
    glass.end_fill()
    glass.setpos(30,20)
    glass.begin_fill()
    for side in range (4):
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(40)
    glass.end_fill()
    glass.setpos(30,60)
    glass.begin_fill()
    for side in range(4):
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(40)
    glass.end_fill()
    glass.setpos(30,100)
    glass.begin_fill()
    for side in range(4):
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(40)
    glass.end_fill()
    glass.setpos(30,140)
    glass.begin_fill()
    for side in range (4):
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(40)
    glass.end_fill()
    glass.setpos(30,180)
    glass.begin_fill()
    for side in range (4):
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(20)
        glass.left(90)
        glass.forward(40)
    glass.end_fill()
    """This is creating the windows of the skyscraper. I needed to make this more concise in some way."""
def door(): #makes the door for the scyscraper
   door=turtle.Turtle()
   door.begin_fill()
   door.hideturtle()
   door.color('brown')
   door.penup()
   door.setpos(90,-70)
   door.left(90)
   door.forward(30)
   door.right(90)
   door.forward(20)
   door.right(90)
   door.forward(30)
   door.right(90)
   door.forward(20)
   door.end_fill()
   """This was needed in order to create a doorway. Creates a brown doorway."""
def Road(): #makes the road
    road=turtle.Turtle()
    road.penup()
    road.hideturtle()
    road.setpos(-300, -100)
    road.pendown()
    road.begin_fill()
    road.forward(600)
    road.right(90)
    road.forward(50)
    road.right(90)
    road.forward(600)
    road.right(90)
    road.forward(50)
    road.end_fill()
    """ Makes the black road."""
def roadline(): #makes the lines on the road
    roadline=turtle.Turtle()
    roadline.hideturtle()
    roadline.penup()
    roadline.color('yellow')
    roadline.setpos(-290, -125)
    for line in range(9):
        roadline.pendown()
        roadline.forward(47)
        roadline.penup()
        roadline.forward(20)
        """Makes the yellow passing lines."""
def main():
    wn = turtle.Screen()
    wn.colormode(255)
    wn.bgcolor('blue')
    drawsquare()
    window1()
    door()
    Road()
    roadline()
    wn.exitonclick()
    """
    Sets up to where we can input values for RGB. Also runs all of the code.
    """
main()

