
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Matthew Foti
# Username: Fotim
#
# Assignment: A03: A Pair of Fully Functional Gitty Psychedelic Robotic Turtles
# Purpose: To understand how to merge successfully
# Google Doc Link: https://github.com/2020-Spring-CSC-226/a03-master
#
#################################################################################
# Acknowledgements:
# Most of the Code was taken from my submission of A02: Loopy Turtles
#
#################################################################################

import turtle
from time import sleep

def move (t, x, y):
    """
    Moves the turtle to a specified location using X, Y coordinate pairs.
    :param t: The turtle to be moved
    :param x: The X coordinate
    :param y: The Y coordinate
    :return: None
    """
    t.up()
    t.setpos(x, y)
    t.down()


def OutsideRing(Outside, i):
    move(Outside, -45, 170)
    while i < 3:  # The loop that creates the outer ring.
        i += 1
        Outside.fd(80)
        Outside.right(80)
        Outside.fd(20)
        Outside.left(65)
        Outside.circle(-100, 90)
        Outside.left(65)
        Outside.fd(20)
        Outside.right(80)
    i = 0





def InnerRing(Inside, i, k):
    move(Inside, -5, 115)
    while i < 3:  # The loop that creates the inner ring.
        i += 1
        Inside.circle(-70, 120)
        Inside.right(90)  # Turns to create each arrow.
        Inside.back(20)
        Inside.fd(60)
        Inside.right(90)
        Inside.fd(10)
        while k < 3:  # The loop that creates the tips of the arrows within the inner ring.
            k += 1
            Inside.left(120)
            Inside.fd(20)
        k = 0
        Inside.back(10)
        Inside.left(90)
        Inside.fd(10)
        Inside.back(50)
        Inside.left(90)  # The end of each arrow





def SCP(Letters):
    move(Letters, -67, -100)  # Draws the S
    Letters.fd(18)
    Letters.back(18)
    Letters.circle(-20, -180)
    Letters.circle(20, -180)
    Letters.back(18)
    move(Letters, 8, -102)  # Draws the C
    Letters.fd(10)
    Letters.back(10)
    Letters.circle(-38, -180)
    Letters.back(10)
    # print(Letters.pos())
    move(Letters, 38, -178)  # Draws the P
    Letters.right(90)
    Letters.fd(60)
    Letters.circle(-20, 270)


def main():
    wn = turtle.Screen()
    Outside = turtle.Turtle()
    Inside = turtle.Turtle()
    Letters = turtle.Turtle()
    i = 0
    k = 0

    Outside.width(10)
    Inside.width(10)
    Letters.width(15)

    wn.bgcolor(0, 0, 0)

    Outside.pencolor(1, 1, 1)
    Inside.pencolor(1, 1, 1)
    Letters.pencolor(1, 1, 1)

    OutsideRing(Outside, i)
    InnerRing(Inside, i, k)
    SCP(Letters)

    wn.exitonclick()


main()

