
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Chris Georgiev
# Username: georgievh
#
# Assignment: HW03
# Purpose: Learn version control using git, and practice using functions by drawing a house
# Google Doc Link:
#
#################################################################################
# Acknowledgements:
# learned about default arguments (used in draw_curve() function) [https://www.geeksforgeeks.org/default-arguments-in-python/]
#
#################################################################################


import turtle


def draw_curve(turty, turn_amount, iterations, direction = "right", line_length = 15):
    """
    Draws a curve by drawing a short line, turning a small amount, then repeating for the length of the curve.
    The shorter the line length the smoother the curve, the greater the turning amount the tighter the curve.
    """
    for i in range(iterations):
        turty.fd(line_length)
        if direction == "right": turty.right(turn_amount)
        if direction == "left": turty.left(turn_amount)

    # ....


def white_circle(turty, radius, forward):
    turty.begin_fill()
    turty.circle(radius)
    turty.fd(forward)
    turty.end_fill()


def draw_background(turty):

    #start on the left side of the screen
    turty.penup()
    turty.setposition(-320,-40)
    turty.pendown()

    #grass color
    turty.fillcolor("green")
    turty.begin_fill()

    #draw grassy ground
    for i in range(8):
        turty.setheading(90)
        draw_curve(turty, 20, 10)

    turty.setheading(270)
    turty.fd(300)
    turty.right(-90)
    turty.fd(-700)
    turty.setposition(-320,-40)
    turty.end_fill()

    #start in upper right
    turty.penup()
    turty.setposition(200, 200)
    turty.pendown()

    #draw sun
    turty.color("yellow")
    turty.begin_fill()
    turty.circle(40)
    turty.end_fill()

    #start in upper left
    turty.penup()
    turty.setposition(-200, 150)
    turty.pendown()

    #draw cloud
    turty.color("white")

    white_circle(turty, 15, 20)
    white_circle(turty, 20, 30)
    white_circle(turty, 20, 30)
    white_circle(turty, 15, 0)

    turty.begin_fill()
    turty.left(90)
    turty.fd(10)
    turty.left(90)
    turty.fd(88)
    turty.left(90)
    turty.fd(10)
    turty.end_fill()


def main():
    """
    Draws picture.
    """
    #setup code
    chris = turtle.Turtle()
    window = turtle.Screen()
    chris.speed("fastest")

    #set sky color
    window.bgcolor("lightblue")

    #do something...
    draw_background(chris)
    #draw_curve(chris, 15, 20, "left")


    #last thing in main
    turtle.exitonclick()


main()  # Starts the program!