# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Janee Amig
# Username: Amigj
#
# Assignment: HW03
# Purpose:
# Google Doc Link: https://docs.google.com/document/d/1ZubPrhdobqaMp-9kqOMK8lZNzvwYkhv42pZEmzof-wU/edit
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################
#Has at least one complex thing which looks like something; a building, animal,  person, etc.
#Is set against a background which is not white. You can use an image or a color as your background.
#Has some embellishments or interesting details, such as windows, text, trees, flowers in front of a house, intricate windows, smoke out of the chimney, or something; these are not all required, they are just suggestions. Be creative!
#Use an unnamed color using either RGB or Hexadecimal.
#Use creativity (such as the use of color, an intricate shape, a cool design…)


import turtle


def function_1():
    """
    Example docstring for function_1. function_1 is not a good function name and should be changed.
    """
    pass
    # ....


def function_2():
    """
    Example docstring for function_2. function_2 is not a good function name and should be changed.
    """
    pass
    # ...


def main():
    """
    Docstring for main. Should describe the main functionality of this file.
    """

    # Function calls to function_1 and function_2.
    function_1()            # TODO  Remove when you replace it with your function
    function_2()            # TODO  Remove when you replace it with your function


main()  # Starts the program!