
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!


#################################################################################
# Author: Leke Bytyqi
# Username: bytyquil
#
# Assignment: t03
# Purpose: Practice functions and learn about source control and Git
# Google Doc Link:https://docs.google.com/document/d/1VNWmdvnYpWDtCOAtIOXUoAWQyeyAr5hSl4PpTTIVu6c/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
# Dr. Heggen
# https://www.rapidtables.com/web/color/RGB_Color.html
#################################################################################



import turtle


# Set up the turtle
flower = turtle.Turtle()
circle = turtle.Turtle()
outsidecircle = turtle.Turtle()
screen = turtle.Screen()
screen.bgcolor ("#E0E0E0")




def draw_petal(color):                      #function for drawing petals of "flower"
   flower.speed(10)
   flower.color(color)
   flower.begin_fill()
   flower.forward(100)
   flower.right(45)
   flower.forward(100)
   flower.right(135)
   flower.forward(100)
   flower.right(45)
   flower.forward(100)
   flower.right(135)
   flower.end_fill()


def flower_circle(circle):              #draws a circle at the middle of the flower petals
   circle.penup
   circle.speed(5)
   circle.goto(0,-20)
   circle.pendown()
   circle.color("black")
   circle.begin_fill()
   circle.circle(20)               #draws a circle of radius 20
   circle.end_fill()
   circle.hideturtle()


def flower_outsidecircle():         #draws a final circlea round the flower
   outsidecircle.penup()
   outsidecircle.goto(0,-200)
   outsidecircle.pendown()
   outsidecircle.speed(10)
   outsidecircle.pensize(10)
   outsidecircle.circle(200)





# Function to draw a flower


colors = ["red", "orange", "yellow", "green", "blue", "purple"]
def draw_flower():          #function for putting the two function together and drawing the final porduct
   for color in colors:    # fills the petals in with th  colors in the variable 'colors'
       draw_petal(color)
       flower.right(60)    # shift the start of the next petal
   flower_circle(circle)   # calls the function flower_circle (circle)
   flower_outsidecircle()  #calls function to draw a cricle around the 'flower'




# Draw the flower and hide cursor
draw_flower()              #calls the fucntion that draws the flower
flower.hideturtle()
flower.penup()


#Prints the intended text on the screen
flower.color("#0F00F0")
flower.setpos(10,-250)
flower.write("Weird Flower Thing!",move=False,align='center',font=("Arial",30,("bold","normal")))




# Close the drawing window when clicked
turtle.exitonclick()