# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Andy Hill
# Username: hilla3
#
# Assignment: HW03
# Purpose: to learn how to push and pull
# Google Doc Link:
#https://docs.google.com/document/d/1kNaw8-ZA9qom9Ylts-O4CE4vvRIhTbGhVIZIhzmSbD4/edit
#################################################################################
# Acknowledgements:
#
#################################################################################

import turtle

cas = turtle.Turtle()

def cassy():
    """Cassy is a friendly turtle. She likes to make lines with her pacing."""
    cas.color("green")
    for i in range(10):
        cas.forward(100)
        cas.right(30)
        cas.backward(130)
    # ....


def cassy_and_friends():
    """
    Docstring for function_2
    """
    for p in range(6):
        cassy()
        cas.left(200)
        cas.forward(50)
    # ...


def main():
    """
    Docstring for main
    """
    wn = turtle.Screen()
    wn.bgcolor("yellow")            # Function call to function_1
    cassy_and_friends()            # Function call to function_2
    wn.exitonclick()

main()


