
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Aliaksandr Melnichenka
# Username: melnichenkaa
#
# Assignment:
# Purpose:
# Google Doc Link: https://docs.google.com/document/d/1SS2cktYFybPYRGyeDuiIRQVh62Jtxf-0xMK6qmmmdfg/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle


def function_1():
    """
    Example docstring for function_1. function_1 is not a good function name and should be changed.
    """
    pass
    # ....


def function_2():
    """
    Example docstring for function_2. function_2 is not a good function name and should be changed.
    """
    pass
    # ...


def main():
    """
    Docstring for main. Should describe the main functionality of this file.
    """

    # Function calls to function_1 and function_2.
    function_1()            # TODO  Remove when you replace it with your function
    function_2()            # TODO  Remove when you replace it with your function


main()  # Starts the program!