
# TODO Do not edit this file directly! Instead, create a new file called
#        hw03_username.py and copy this code into it!

#################################################################################
# Author: Sugarragchaa Tumur-Ochir
# Username: Sugargod1
#
# Assignment: hw03_Sugargod1
# Purpose: Better understanding of git and Github
# Google Doc Link: https://docs.google.com/document/d/17NHKwPKQIHpA5JfAf-XqfP_sFllP3Gk8PNOkkDWPsdk/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
# screen function determines screen color
# housebody function make house's body
# roofy makes roof
# doory makes the door
# windowy makes the window
# we only used one hardworking turtle, he does them all
# I'm currently working on my datascience and algorithm skill's so I didn't show much creativity in it. UwU feeling guilty.
#################################################################################

import turtle

def screen(wn):
    wn.bgcolor("#7B68EE")
def housebody(turti):
    turti.pencolor('orange')
    turti.penup()
    turti.goto(200, 50)
    turti.pendown()
    turti.left(180)
    turti.pensize(15)
    turti.begin_fill()
    turti.fillcolor('orange')
    turti.begin_fill()
    for i in range(4):  # Making a rectangular door
        turti.forward(400)
        turti.left(90)
    turti.end_fill()
def roofy(turti):
    turti.fillcolor('pink')
    turti.penup()
    turti.goto(-210, 50)
    turti.pendown()
    turti.right(180)
    turti.pencolor('blue')
    turti.begin_fill()
    for i in range(3):  # Making a rectangular door
        turti.forward(420)
        turti.left(120)
    turti.end_fill()
def doory(turti):
    turti.penup()
    turti.goto(-60, -365)
    turti.pendown()
    turti.pencolor('brown')
    turti.begin_fill()
    turti.forward(140)
    turti.left(90)
    turti.forward(280)
    turti.left(90)
    turti.forward(140)
    turti.left(90)
    turti.forward(280)
    turti.end_fill()
def windowy(turti):
    turti.penup()
    turti.goto(-200, 0)  # Position the turtle to draw the horizontal line
    turti.pendown()
    turti.pensize(5)
    turti.pencolor('white')
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(-160, 0)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(-200, -40)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(-160, -40)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(110, 0)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(150, 0)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(110, -40)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)
    turti.penup()
    turti.goto(150, -40)  # Position the turtle to draw the horizontal line
    turti.pendown()
    for i in range(4):
        turti.forward(40)
        turti.left(90)


def main():
    AlphaTurtle = turtle.Turtle()
    wn = turtle.Screen()
    screen(wn)
    housebody(AlphaTurtle)
    roofy(AlphaTurtle)
    doory(AlphaTurtle)
    windowy(AlphaTurtle)
    turtle.exitonclick()
main()