
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Relly Gray
# Username: grayr2
#
# Assignment:
# Purpose:
# Google Doc Link: https://docs.google.com/document/d/1UVBNWf08HXY_rivdGX1H_HSzcBGa33XGG7AeElADZLg/edit?usp=sharing
#
#################################################################################
# Acknowledgements: ChatGpt
# I asked chatgpt how it may be possible to turn my shape into a skyscraper and it gave me back this: rell.setpos(-100, 100 - (floor + 1) * floor_height)  # Adjust position for the next floor
#
#################################################################################


import turtle

rell = turtle.Turtle()
rell.speed(10)

def skyscraper():
    """
    Example docstring for function_1. function_1 is not a good function name and should be changed.
    """
    pass
    rell.color("grey")
    rell.penup()
    rell.setpos(-100, 200)
    rell.pendown()
    rell.pensize(5)
    floor = 10
    floor_height = 50
    rell.begin_fill()
    for floor in range(4):
        rell.fd(200)
        rell.right(90)
    rell.penup()
    rell.setpos(-100, 200 - (floor + 1) * floor_height)  # Adjust position for the next floor
    rell.pendown()
    for floor in range (4):
        rell.fd(300)
        rell.right(90)
    rell.end_fill()

def windows():
    """
    Example docstring for function_2. function_2 is not a good function name and should be changed.
    """
    pass
    rell.pensize(1)
    rell.color("lightblue")
    rell.penup()
    rell.setpos(-90, 190)
    rell.pendown()
    rell.begin_fill()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(-90, 130)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(-90, 70)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(-30, 190)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(-30, 130)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(-30, 70)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(30, 190)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(30, 130)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
    rell.penup()
    rell.setpos(30, 70)
    rell.pendown()
    for windows in range(4):
        rell.fd(40)
        rell.right(90)
# the bottom layer of windows starts here (includes door and text)
    rell.penup()
    rell.setpos(-90, -10)
    rell.pendown()
    for windows in range(2):
        rell.fd(280)
        rell.right(90)
        rell.fd(70)
        rell.right(90)
    rell.penup()
    rell.setpos(-90, -90)
    rell.pendown()
    for windows in range(2):
        rell.fd(280)
        rell.right(90)
        rell.fd(70)
        rell.right(90)
    rell.penup()
    rell.setpos(-90, -170)
    rell.pendown()
    for windows in range(2):
        rell.fd(280)
        rell.right(90)
        rell.fd(70)
        rell.right(90)
# the door
    rell.penup()
    rell.setpos(0, -270)
    rell.pendown()
    rell.color("white")
    for windows in range(2):
        rell.fd(50)
        rell.right(90)
        rell.fd(30)
        rell.right(90)
    rell.penup()
    rell.setpos(-90, 230)
    rell.pendown()
    rell.color(0, 0, 0)
    rell.hideturtle()
    rell.write("Welcome to Turtle Inc.", (30))

def main():
    """
    Docstring for main. Should describe the main functionality of this file.
    """
    wn = turtle.Screen()
    wn.bgcolor("#8BF2FD")
    # Function calls to function_1 and function_2.
    skyscraper()

    wn.exitonclick()

main()  # Starts the program!