
# TODO Do not edit this file directly! Instead, create a new file called
#        hw03_username.py and copy this code into it!

#################################################################################
# Author: Nauryzbek Berdi
# Username: berdin
#
# Assignment: hw03
# Purpose: Continuing practicing creating and using functions; learning about git, colors, and turtle library
# Google Doc Link: https://docs.google.com/document/d/1bgYDH434Ups0uL581DnplAQ8lvTZ0lSUzPs7fsjDu14/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle


def moon_code():
    """
    this function draws a circle with the moon color
    """
    moon = turtle.Turtle()
    moon.hideturtle()
    moon.speed(0)

    moon.penup()
    moon.goto(0, 300)                       # going up to draw the moon
    moon.pendown()

    moon.color('#dcdcdc')                         # color of the moon
    moon.begin_fill()
    moon.circle(60)                               # circle of the moon
    moon.end_fill()


def house_code():
    """
        this function draws the body of the house and fill it with wall color
    """
    house = turtle.Turtle()
    house.hideturtle()
    house.speed(0)

    house.penup()
    house.goto(-400, -250)
    house.pendown()

    house.color('#c3c4c2')                        # wall color of body house
    house.begin_fill()
    house.forward(800)                            # body of house starts here
    house.left(90)
    house.forward(300)
    house.left(90)
    house.forward(325)
    house.right(60)
    house.forward(150)
    house.left(120)
    house.forward(150)
    house.right(60)
    house.forward(325)
    house.left(90)
    house.forward(300)                            # body of house ends here
    house.end_fill()


def roof_code():
    """
        this function draws the roof of the house and fill it with another wall color like gray
    """
    roof = turtle.Turtle()
    roof.hideturtle()
    roof.speed(0)

    roof.penup()
    roof.goto(77, 50)
    roof.pendown()

    roof.color('#888a89')                          # wall color of roof house
    roof.begin_fill()
    roof.forward(360)                              # roof of house starts here
    roof.circle(20, 90)
    roof.forward(150)
    roof.left(45)
    roof.forward(60)
    roof.right(45)
    roof.forward(45)
    roof.right(90)
    roof.forward(43)
    roof.right(90)
    roof.forward(87)
    roof.right(-45)
    roof.backward(60)
    roof.right(135)
    roof.forward(700)
    roof.right(70)
    roof.forward(80)
    roof.left(75)
    roof.forward(40)
    roof.left(90)
    roof.forward(80)
    roof.right(95)
    roof.forward(80)
    roof.circle(20, 90)
    roof.forward(165)
    roof.circle(20, 90)
    roof.forward(349)
    roof.left(63)
    roof.forward(170)
    roof.right(125)
    roof.forward(170)                                 # body of house ends here
    roof.end_fill()


def little_window_code():
    """
        this function draws a little white window above the door
    """
    little_window = turtle.Turtle()
    little_window.hideturtle()
    little_window.speed(0)

    little_window.penup()
    little_window.goto(-20, 50)                    # little window on the top of the house
    little_window.pendown()
    little_window.color('white')
    little_window.forward(40)
    little_window.left(150)
    little_window.forward(46)
    little_window.left(120)
    little_window.forward(23)
    little_window.left(120)
    little_window.forward(45)
    little_window.left(149)
    little_window.forward(40)
    little_window.penup()
    little_window.backward(40)
    little_window.pendown()
    little_window.left(90)
    little_window.forward(23)                          # the little window ends here


def door_code():
    """
        this function draws the brown door with its handle
    """
    door = turtle.Turtle()
    door.hideturtle()
    door.speed(0)

    door.penup()                                       # main door starts here; goes down
    door.goto(-30, -200)
    door.pendown()
    door.color('#b76f20')                              # color of the door (brown)
    door.begin_fill()
    for i in range(2):
        door.forward(70)
        door.left(90)
        door.forward(150)
        door.left(90)
    door.end_fill()  # the door ends here

    door.penup()  # the door handle
    door.right(90)
    door.backward(70)
    door.pendown()
    door.left(90)
    door.penup()
    door.forward(8)
    door.pendown()
    door.color('#738678')  # sets xandu color
    door.begin_fill()
    door.circle(4)
    door.end_fill()  # the handle ends here


def left_window_code():
    """
        this function draws two white windows of the house on the left side
    """
    left_window = turtle.Turtle()
    left_window.hideturtle()
    left_window.speed(0)

    left_window.penup()
    left_window.goto(-300, -160)                       # goes down to start drawing the left window
    left_window.pendown()
    left_window.color('white')                         # sets white color
    for i in range(2):
        left_window.forward(70)                            # the first code of left window starts here
        left_window.left(90)
        left_window.forward(90)
        left_window.left(90)
    left_window.forward(35)
    left_window.left(90)
    left_window.forward(90)
    left_window.left(90)
    left_window.forward(35)
    left_window.left(90)
    left_window.forward(45)
    left_window.left(90)
    left_window.forward(70)                            # the first code of left window ends here

    left_window.penup()
    left_window.forward(30)
    left_window.pendown()
    left_window.right(90)                              # the second code of left window starts here
    left_window.forward(45)
    left_window.left(90)
    left_window.forward(70)
    left_window.left(90)
    left_window.forward(90)
    left_window.left(90)
    for i in range(2):
        left_window.forward(70)
        left_window.left(90)
        left_window.forward(45)
        left_window.left(90)
    left_window.forward(35)
    left_window.left(90)
    left_window.forward(90)                            # the second code of left window ends here


def right_window_code():
    """
        this function draws one white window of the house on the right side
    """
    right_window = turtle.Turtle()
    right_window.hideturtle()
    right_window.speed(0)

    right_window.penup()
    right_window.goto(200, -160)
    right_window.pendown()
    right_window.color('white')                        # sets white color
    for i in range(2):
        right_window.forward(70)                           # the code of right window starts here
        right_window.left(90)
        right_window.forward(90)
        right_window.left(90)
    right_window.forward(35)
    right_window.left(90)
    right_window.forward(90)
    right_window.left(90)
    right_window.forward(35)
    right_window.left(90)
    right_window.forward(45)
    right_window.left(90)
    right_window.forward(70)                            # the code of right window ends here


def road_left_side_code():
    """
        this function draws left yellow line of the road in front of the house
    """
    road_left_side = turtle.Turtle()
    road_left_side.hideturtle()
    road_left_side.speed(0)

    road_left_side.color('yellow')                     # the left line of road code starts here
    road_left_side.penup()
    road_left_side.goto(-30, -250)
    road_left_side.pendown()
    road_left_side.right(120)
    road_left_side.forward(220)                        # the left line of road code ends here


def road_right_side_code():
    """
        this function draws right yellow line of the road in front of the house
    """
    road_right_side = turtle.Turtle()
    road_right_side.hideturtle()
    road_right_side.speed(0)

    road_right_side.color('yellow')                    # the right line of road code starts here
    road_right_side.penup()
    road_right_side.goto(30, -250)
    road_right_side.pendown()
    road_right_side.right(100)
    road_right_side.forward(200)                       # the right line of road code ends here


def main():
    """
        this function is main function, which calls other functions step by step
    """

    wn = turtle.Screen()
    wn.bgcolor('#2e4482')

    moon_code()
    house_code()
    roof_code()
    little_window_code()
    door_code()
    left_window_code()
    right_window_code()
    road_left_side_code()
    road_right_side_code()

    wn.exitonclick()


main()                                                 # Starts the program!
