
# TODO Do not edit this file directly! Instead, create a new file called
# TODO a03_username.py and copy this code into it!

#################################################################################
# Author: Nathan Jiang
# Username: jiangn
#
# Assignment: HW03: Fully Functional Gitty Psychedelic Robotic Turtles
# Purpose:
# Google Doc Link: https://docs.google.com/document/d/1mW0EGrnFAPqNFa9dmLd6rhSoid9egv5q2nd8wSHP0t8/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle


def drawbox(t1):
    """
    Creates a box for the house
    """
    t1.speed(0)
    t1.penup()
    t1.setpos(-200,-200)
    t1.color("black")
    t1.shape("square")
    t1.pensize(15)
    t1.pendown()
    t1.forward(400)
    t1.left(90)
    t1.forward(270)
    t1.left(90)
    t1.forward(400)
    t1.left(90)
    t1.forward(270)
    # ....


def drawroof(t2):
    """
    Draws a roof on the house
    """
    t2.speed(0)
    t2.penup()
    t2.pensize(15)
    t2.color("black")
    t2.shape("square")
    t2.setpos(-200,70)
    t2.pendown()
    t2.left(45)
    t2.forward(283)
    t2.right(90)
    t2.forward(283)
    # ...


def main():
    """
    Creates a window and initializes t1 and t2.
    """
    wn = turtle.Screen()
    t1 = turtle.Turtle()
    t2 = turtle.Turtle()

    drawbox(t1)
    drawroof(t2)

    wn.exitonclick()

main()

