# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Aije Ebosele
# Username: eboselea
#
# Assignment: HW03  - Fully Functioning Gitty Pychedelic Robotic Turtles
# Purpose: Gain more pratice with turtles and fuctions,
# Google Doc Link: https://docs.google.com/document/d/16Y0xEFJ3f_ICamBh3k_8JRpmHmy1obomjudzBOIt6rE/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle


def function_1():
    """
    Example docstring for function_1. function_1 is not a good function name and should be changed.
    """
    pass
    # ....


def function_2():
    """
    Example docstring for function_2. function_2 is not a good function name and should be changed.
    """
    pass
    # ...


def main():
    """
    Docstring for main. Should describe the main functionality of this file.
    """
    wn = turtle.Screen()
    wn.colormode(255)
    wn.bgpic("Street.gif")
    shape = turtle.Turtle()
    
    
    # Function calls to function_1 and function_2.
    function_1()
    function_2()


main()  # Starts the program!