
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Austin Weiner
# Username: Weinera
#
# Assignment: H03
# Purpose: To learn?
# Google Doc Link: https://docs.google.com/document/d/1XWzba1pEjGnsw3oemtC4DIPApPrqgqTjvhZ4X6tWoGg/edit?tab=t.0#heading=h.ju96mtye4s7l
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

#################################################################################
# Header
#################################################################################
import turtle

def main():
#Setting everything up
    wn = turtle.Screen()
    wn.bgpic("wp2775443.gif")
    base()
    treat()
    wn.exitonclick()

#Building the base
def base():
    pass
#Setting the turtle up
    builder_base = turtle.Turtle()
    builder_base.pensize(20)
    builder_base.teleport(-100,0)
    builder_base.color("#B29569")

#Building the outer cone
    builder_base.fillcolor("#B68A50")
    builder_base.begin_fill()
    builder_base.right(60)
    builder_base.fd(200)
    builder_base.left(120)
    builder_base.fd(200)
    builder_base.left(120)
    builder_base.fd(200)
    builder_base.end_fill()

#Horizontal lines
    builder_base.pensize(5)
    #Horizontal Line 1
    builder_base.teleport(70,-30)
    builder_base.forward(140)

    #Horizontal Line 2
    builder_base.teleport(60,-50)
    builder_base.fd(130)

    #Horizontal Line 3
    builder_base.teleport(50,-70)
    builder_base.fd(110)

    #Horizontal Line 4
    builder_base.teleport(40, -100)
    builder_base.fd(90)

    #Horizontal Line 5
    builder_base.teleport(30, -130)
    builder_base.fd(60)

#Vertical Lines
    builder_base.left(90)
    #Vertical Line 1
    builder_base.teleport(-50, 0)
    builder_base.fd(100)

    #Vertical Line 2
    builder_base.teleport(-20, 0)
    builder_base.fd(130)

    #Vertical Line 3
    builder_base.teleport(10, 0)
    builder_base.fd(150)

    #Vertical Line 4
    builder_base.teleport(40, 0)
    builder_base.fd(120)

    #Hiding the turtle
    builder_base.hideturtle()

def treat():
    pass
#Setting up the turtle
    ice = turtle.Turtle()
    ice.pensize(20)
    ice.pencolor("#E27FBA")

#Build circle
    ice.teleport(0,-30)
    ice.fillcolor("#DCA1C5")
    ice.begin_fill()
    ice.circle(100)
    ice.end_fill()
#Hiding turtle
    ice.hideturtle()
main()