import turtle

# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Ryan Hensley
# Username:hensleyr2
#
# Assignment: HW_03
# Purpose: homework
# Google Doc Link: https://docs.google.com/document/d/1X-Azk1gf3abSbWXfyt8G18eT6I5-9YBWFkyrgcs1Ohg/edit?tab=t.0#heading=h.j4414z2ufr72
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle


bob = turtle.Screen()
#spawn gif
bob.bgpic("grass.gif")



#turtle for flower and fill
rain = turtle.Turtle()
rain.speed(10)
rain.teleport(-100 ,50)
rain.color('white')
rain.pensize(10)
rain.begin_fill()
#Make flower
for i in range(10):
    rain.forward(200)
    rain.left(200)

rain.end_fill()
#Turtle for stem.
storm = turtle.Turtle()
storm.pensize(10)
storm.color('brown')
storm.right(90)
storm.forward(150)
storm.speed(10)

#turtle to fill center
alex = turtle.Turtle()
alex.teleport(0,30)
alex.color("#BD9805")
alex.shape("circle")
alex.shapesize(2)

bob.exitonclick()



