
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Julius Fritz
# Username: Fritzj2
#
# Assignment: hw03
# Purpose: Learn to use git and github to push and pull branches, get feedback, and get more practice with turtle
# Google Doc Link: https://docs.google.com/document/d/11-bhBE_z4YSAgW-Wrwi5ediloF5m-LBPOzNu8RYMyJ0/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle
import random

def Trunk_Draw():
    trunk = turtle.Turtle()
    trunk.shape("square")
    trunk.color("brown")
    trunk.speed(0) #TODO Change this off of 0
    trunk.teleport(450, 150)
    trunk.begin_fill()
    trunk.right(90)
    trunk.circle(50,100)
    trunk.left(350-180)
    trunk.forward(300)
    trunk.right(180)
    trunk.circle(50,89.95)
    #This is the code for the base of the trunk with the curves
    trunk.right(10)
    trunk.fd(300)
    trunk.right(80)
    trunk.forward(95)
    trunk.end_fill()
    trunk.pensize(1)
    trunk.teleport(-250,0)


    #Draws the trunk of the tree
    pass

def Trunk_texture():
    texture = turtle.Turtle()
    texture.color(0.44,0.09,0.04)
    texture.speed(0)
    texture.pensize(2)
    texture.right(90)
    for i in range(15):
        texture.teleport(random.randint(315, 400),random.randint(400,425))
        texture.forward(random.randint(175, 300))
    #this makes a random texture pattern on the tree
    texture.teleport(-250, 0)


    pass
def Trunk_Hole():
    hole = turtle.Turtle()
    hole.color('black')
    hole.speed(0)
    hole.teleport(325, 250)
    hole.begin_fill()
    hole.circle(25)
    hole.end_fill()
    hole.teleport(-250,0)
    wn = turtle.Screen()
    wn.exitonclick()
    #Creates the hole on the tree

def main():
    wn = turtle.Screen()
    turtle.setworldcoordinates(0, 0, 800, 600)
    wn.bgcolor("pink")


    # Function calls to function_1 and function_2.
    Trunk_Draw()
    Trunk_texture()
    Trunk_Hole()
    #TODO Add the final function with the leaves

main()  # Starts the program!