
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Yuki Fukushima
# Username: fukushimay
#
# Assignment: hw03, Task 2
# Purpose: Build haunted house
# Google Doc Link: https://docs.google.com/document/d/1kCOYZlehfE9XLhcFp7Q2oucXEcMcs-9kNhGL07GFZx0/edit?usp=sharing
#
#################################################################################


import random
import turtle

def draw_land(tur):
    tur.teleport(-320, 0)
    turtle.colormode(255)
    tur.fillcolor(33, 106, 23)

    tur.begin_fill()

    tur.forward(700)
    tur.right(90)
    tur.forward(500)
    tur.right(90)
    tur.forward(700)
    tur.right(90)
    tur.forward(500)

    tur.end_fill()

    tur.right(90)


def draw_house(tur,wn):
    """
    Example docstring for function_1. function_1 is not a good function name and should be changed.
    """
    turtle.colormode(255)
    tur.fillcolor(6, 25, 45)

    tur.begin_fill()

    tur.teleport(-100, -100)

    for i in range(4):
        tur.forward(200)
        tur.left(90)

    tur.end_fill()

    """Add Windows"""

    def left_window(tur):
        tur.teleport(-80, 80)
        tur.fillcolor(255, 166, 42)

        tur.begin_fill()

        for i in range(4):
            tur.forward(50)
            tur.right(90)

        tur.end_fill()

        tur.forward(25)
        tur.right(90)
        tur.forward(50)
        tur.left(90)
        tur.forward(25)
        tur.left(90)
        tur.forward(25)
        tur.left(90)
        tur.forward(50)

    def right_window(tur):
        tur.teleport(30, 80)
        tur.fillcolor(255, 166, 42)
        tur.right(180)

        tur.begin_fill()

        for i in range(4):
            tur.forward(50)
            tur.right(90)

        tur.end_fill()

        tur.forward(25)
        tur.right(90)
        tur.forward(50)
        tur.left(90)
        tur.forward(25)
        tur.left(90)
        tur.forward(25)
        tur.left(90)
        tur.forward(50)

    left_window(tur)
    right_window(tur)

    """Add door frame"""
    tur.teleport(-50, -100)
    tur.fillcolor(162, 162, 162)
    tur.right(180)

    tur.begin_fill()

    tur.left(90)
    tur.forward(100)
    tur.right(90)
    tur.forward(100)
    tur.right(90)
    tur.forward(100)
    tur.left(90)

    tur.end_fill()

    """Add ghost"""
    wn.addshape("ghost.gif")

    ghost = turtle.Turtle()
    ghost.shape("ghost.gif")
    ghost.penup()
    ghost.goto(0, -50)



def draw_roof(tur):
    """
    Example docstring for function_2. function_2 is not a good function name and should be changed.
    """

    tur.teleport(-140, 100)

    turtle.colormode(255)
    tur.fillcolor(68, 55, 37)

    tur.begin_fill()

    tur.forward(280)
    tur.left(135)
    tur.forward(200)
    tur.left(90)
    tur.forward(200)

    tur.end_fill()

    # ...

def draw_chimney(tur):

    """Draws smoke first"""
    for i in range(10):
        x = random.randint(80, 120)
        y = random.randint(220, 300)
        tur.teleport(x, y)
        tur.dot(40, "gray")

    """Draws a rectangular chimney"""
    tur.teleport(80, 160)
    turtle.colormode(255)
    tur.fillcolor(14, 11, 6)

    tur.begin_fill()

    tur.right(135)
    tur.forward(50)
    print(tur.position())
    tur.right(90)
    tur.forward(30)
    tur.right(90)
    tur.forward(80)

    tur.end_fill()

def draw_moon(tur):
    tur.teleport(-300, 200)
    tur.fillcolor("yellow")

    tur.begin_fill()

    tur.circle(60)

    tur.end_fill()

    tur.penup()
    tur.teleport(-325, 220)
    tur.fillcolor(36, 17, 61)

    tur.begin_fill()

    tur.circle(60)

    tur.end_fill()

def main():
    """
    Docstring for main. Should describe the main functionality of this file.
    """
    wn = turtle.Screen()
    wn.colormode(255)
    wn.bgcolor(36, 17, 61)
    wn.screensize(500, 500)
    tur = turtle.Turtle()

    # Function calls to function_1 and function_2.
    draw_land(tur)
    draw_house(tur, wn)            # TODO  Remove when you replace it with your function
    draw_roof(tur)  # TODO  Remove when you replace it with your function
    draw_chimney(tur)
    draw_moon(tur)

    print(wn.screensize())

    wn.exitonclick()


main()  # Starts the program!