
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Mach Riak Garang
# Username: Mach
#
# Assignment: HW03_Mach
# Purpose:Running the turtle
# Google Doc Link:https://docs.google.com/document/d/1Tax5yLhQKAq7F3-GVT1UV2F5nFAJsY-fT-p5dtSw01s/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################

import turtle

def function_1(color, shape):
    t = turtle.Turtle()
    t.color(color)
    t.shape(shape)
    return t


def function_2(screen_color, back_ground_color):
    wn = turtle.Screen()
    wn.bgcolor(back_ground_color)
    return wn


def create_square(t):
    t.begin_fill()
    for _ in range(4):
        t.forward(100)
        t.right(90)
    t.end_fill()

def main():
    t = function_1("black", "turtle")
    function_2("green", "white")
    create_square(t)
    t.fillcolor()
    turtle.done()


if __name__ == "__main__":
    main()

  # Starts the program!