
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Mach Riak Garang
# Username: Mach
#
# Assignment: HW03_Mach
# Purpose:Running the turtle
# Google Doc Link:https://docs.google.com/document/d/1Tax5yLhQKAq7F3-GVT1UV2F5nFAJsY-fT-p5dtSw01s/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
#
#
#################################################################################


import turtle


def function_1(color, shape):
    t=turtle.Turtle()
    t.color(color)
    t.shapesize(shape)
    pass
    # ....


def function_2(screen_color, back_ground_color):
    wn = screen.Screen()
    wn.bgcolor(back_ground_color)
    wn.color(screen_color)
    pass
    # ...


def main():

    # Function calls to function_1 and function_2.
    function_1("black","turtle")            #TODO  Remove when you replace it with your function
    function_2("green", "white")            #TODO  Remove when you replace it with your function


    main()  # Starts the program!