
# TODO Do not edit this file directly!
# TODO Instead, create a new file called hw03_username.py and copy this code into it!

#################################################################################
# Author: Bryanna Moreno Casas
# Username: morenocasasb
#
# Assignment: HW03: Fully Functional Gitty Psychedelic Robotic Turtles
# Purpose: Drawing a house, clouds, and a window
# Google Doc Link: https://docs.google.com/document/d/1Ur1ytmgXB2Is1zB4L2Pj6cbs9VvplddQcrZqto6H7D4/edit?usp=sharing
#
#################################################################################
# Acknowledgements:
# https://docs.python.org/3/library/turtle.html#turtle.setpos
#
#################################################################################


import turtle


def house():                            # This whole function creates a house
    def housebase():                    # This one is the base of the house
        base = turtle.Turtle()
        base.color("#775F1B")
        base.penup()
        base.setx(-150)
        base.sety(-260)
        base.begin_fill()
        base.pendown()
        base.left(90)
        base.forward(300)
        base.right(90)
        base.forward(300)
        base.right(90)
        base.forward(300)
        base.end_fill()

    def housedoor():                    # This one creates a door
        door = turtle.Turtle()
        door.penup()
        door.setx(100)
        door.sety(-260)
        door.pendown()
        door.color("#493809")
        door.begin_fill()
        door.left(90)
        door.forward(100)
        door.left(90)
        door.forward(50)
        door.left(90)
        door.forward(100)
        door.end_fill()

    housebase()
    housedoor()

def windowhouse():                       # Decided to use this function as a window
    def outsidewindow():                # This function creates the frame of the window
        window = turtle.Turtle()
        window.color("white")
        window.pensize(5)
        window.penup()
        window.setx(-100)
        window.sety(0)
        window.pendown()
        window.forward(150)
        window.right(90)
        window.forward(150)
        window.right(90)
        window.forward(150)
        window.right(90)
        window.forward(150)
        window.penup()
        window.right(90)
        window.forward(75)
        window.right(90)
        window.pendown()
        window.forward(150)
        window.penup()
        window.right(90)
        window.forward(75)
        window.right(90)
        window.forward(75)
        window.pendown()
        window.right(90)
        window.forward(150)

    def insidewindow():                  # This kind of makes the illusion of a glass window (I think)
        glass = turtle.Turtle()
        glass.color("#92EEFF")
        glass.begin_fill()
        glass.pensize(5)
        glass.penup()
        glass.setx(-100)
        glass.sety(0)
        glass.pendown()
        glass.forward(150)
        glass.right(90)
        glass.forward(150)
        glass.right(90)
        glass.forward(150)
        glass.right(90)
        glass.forward(150)
        glass.end_fill()

    insidewindow()
    outsidewindow()


def main():                             # This function creates a background
    wn = turtle.Screen()
    wn.bgcolor("#7ACDDE")

    cloud = turtle.Turtle()
    cloud.penup()
    cloud.setx(130)
    cloud.sety(130)
    cloud.pendown()

    def clouds():                       # This is a function within a function.
        cloud.color("white")            # I'm using this function to plan the motion of the clouds
        cloud.begin_fill()              # I have created two clouds that would need to use this function
        cloud.forward(150)
        cloud.left(90)
        cloud.forward(40)
        cloud.left(45)
        cloud.forward(40)
        cloud.left(45)
        cloud.forward(40)
        cloud.left(45)
        cloud.forward(40)
        cloud.right(90)
        cloud.forward(40)
        cloud.left(45)
        cloud.forward(40)
        cloud.left(90)
        cloud.forward(60)
        cloud.left(55)
        cloud.forward(20)
        cloud.end_fill()

    clouds()                            # Function within the function #1

    cloud.penup()
    cloud.setx(-200)
    cloud.left(35)
    cloud.pendown()

    clouds()                            # Function within the function #2


    # Function calls to function_1 and function_2.
    house()            # TODO  Remove when you replace it with your function
    windowhouse()            # TODO  Remove when you replace it with your function

    wn.exitonclick()

main()  # Starts the program!